version: '3.8'

services:
  # Nagios Core
  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "8080:80"
    volumes:
      - nagios_data:/opt/nagios/etc
      - nagios_var:/opt/nagios/var
    environment:
      - NAGIOS_TIMEZONE=UTC
      - NAGIOS_ADMIN_USER=admin
      - NAGIOS_ADMIN_PASS=admin123
    restart: unless-stopped
    networks:
      - monitoring_net

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - monitoring_net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - monitoring_net

  # Node Exporter (for Prometheus metrics)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring_net

volumes:
  nagios_data:
  nagios_var:
  prometheus_data:
  grafana_data:

networks:
  monitoring_net:
    driver: bridge