version: '3.8'

services:
  # Nagios Core
  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "8080:80"
    volumes:
      - nagios_etc:/opt/nagios/etc
      - nagios_var:/opt/nagios/var
    environment:
      - NAGIOS_TIMEZONE=UTC
    restart: unless-stopped
    networks:
      - monitoring_net

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - .process_to_prometheus.sh:/process_to_prometheus.sh
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - monitoring_net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    restart: unless-stopped
    networks:
      - monitoring_net

  # Node Exporter
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    volumes:
       - /home/ubuntu/monitoring-vol/node_exporter:/var/lib/node_exporter
    command:
      - '--collector.textfile.directory=/var/lib/node_exporter'
      - '--collector.textfile'
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring_net

volumes:
  nagios_etc:
    driver: local
    driver_opts:  
      type: none
      o: bind
      device: /home/ubuntu/monitoring-vol/nagios/etc
  nagios_var:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/monitoring-vol/nagios/var
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/monitoring-vol/prometheus/data
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/monitoring-vol/grafana/data

networks:
  monitoring_net:
    driver: bridge