services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}
      - xpack.security.http.ssl.enabled=${XPACK_SECURITY_SSL_ENABLED}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.ml.use_auto_machine_memory_percent=${XPACK_ML_MEMORY_PERCENT}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
      - ./settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      - xpack.monitoring.elasticsearch.hosts=${LOGSTASH_MONITORING_HOSTS}
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USERNAME=${KIBANA_ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      - elasticsearch

volumes:
  es_data: